### ISSUE TITLE
Distance attenuation

### ISSUE THREAD

**Issue by alekseyt** [pezcode/Cluster#5]
This is not a big deal, it's rather a question. There is this function in `lights.sh`:

```glsl
float distanceAttenuation(float distance)
{
    // only for point lights

    // physics: inverse square falloff
    // pretend point lights are tiny spheres of 1 cm radius
    return 1.0 / max(distance * distance, 0.01 * 0.01);
}
```

Comment says "pretend point lights are tiny spheres of 1 cm radius", is that correct though? To me it looks like at distance `1.0` attenuation is going to be `1.0` because `1.0 / (1.0 * 1.0) == 1.0`, am i right? 

Shouldn't there be a falloff at 1m distance if lights are 1cm, or what are the units of distance?

I've changed it locally to this:

```glsl
float distanceAttenuation(float distance)
{
    // only for point lights

    // physics: inverse square falloff
    // pretend point lights are tiny spheres of zero radius
    return 1.0 / ((distance + 1) * (distance + 1));
}
```

So at distance 1m there will be `0.25` falloff factor and i've got this picture:

![Без имени](https://user-images.githubusercontent.com/993454/73601653-045acc80-456e-11ea-8007-45c0a3e0e662.png)

Above is vanilla Cluster, below modified. Note that there are no bright spots of (almost?) white light in the middle of point lights anymore.

Should those bright spots be there?

**Comment by pezcode** [comment]
I admit that comment is a bit poorly worded without knowing the motivation behind it.

The falloff is meant to scale the light intensity, which is defined as energy per unit solid angle per second. The further you get from the light source, the less energy you have arriving at an equally sized area (the pixel in this case). The value of intensity you give your light then defines the energy arriving at a pixel at unit distance. Unit distance is just anything that is 1 x away (here x is meters).

Anything closer than 1 meter ends up having falloff values greater than 1. Since point lights are inherently physically incorrect, you can end up being so close to the light source that the final radiance just blows up towards infinity. To correct for that, you can limit the intensity to a maximum at, let's say 1cm away. That's what the `max` above does.

What you changed it to is a physically incorrect falloff that happens to produce lower radiance values and looks more pleasing. The reason the lights appear to have the same radius is the windowing function that artificially limits the radius to allow for culling (otherwise, you'd get huge radiuses or visible cutoff artifacts).

If you haven't yet, I really recommend reading the [Frostbite PBR course notes](https://seblagarde.files.wordpress.com/2015/07/course_notes_moving_frostbite_to_pbr_v32.pdf). They are unbelievably helpful for wrapping your head around all the units and calculations involved. Your question also gets answered on page 28 and 29 there.

**Comment by alekseyt** [comment]
Very interesting read, thank you. So point light is kind of emulating light coming from a star's surface. Although i still think there is a mistake, maybe in that paper too. This picture:

![image](https://user-images.githubusercontent.com/993454/73615214-09c02180-4617-11ea-9a3f-781a98c53c9c.png)

shows that at distance 2r flux should be squared, but in their example r = 1cm thus 2r = 2cm, so falloff factor can't be 1.0 at distance 1m, it should already have a falloff at that distance if it follows inverse square law. According to their formula, point light is a sphere of radius 1m with intensity going up inside sphere (with cutoff at 1cm) and falling off rapidly outside that sphere. It's just that language says one thing, but math says another thing.

OK, whatever, i'm going to close this issue. Thank you again for the link, as i said, very interesting read, i'll go through it.

**Comment by alekseyt** [comment]
I don't want to open another issue, but i would like to reiterate on it if that's possible. I've noticed that in recent changes `struct PointLight` got new member `_padding`. Is that possible to reserve this member for light source size instead?

Right now `lights.sh` sort of assumes that point light size is 1 cm (0.01) as described above, however i still believe that this is not the size of light source, but a cutoff where attenuation stops growing towards infinity. If this member is used for size, then this can be possibly resolved externally by setting up another light size which is considered most appropriate.

Attenuation function would be something like this:

```glsl
float distanceAttenuation(float distance, float size)
{
    // only for point lights

    // physics: inverse square falloff
    // pretend point lights are tiny spheres of <size> radius
    // with hard cutoff at 0.01 (1 cm)
    return 1.0 / max((distance - size + 1) * (distance - size + 1), 0.01 * 0.01);
}
```

And default size would be 1 m (one meter). For comparison, here is original image from unpatched Cluster:

![image](https://user-images.githubusercontent.com/993454/78951667-95ed3a00-7adb-11ea-887e-b2a3e3bc1a65.png)

Here is image from patched Cluster with each point light size set to 1 meter:

![image](https://user-images.githubusercontent.com/993454/78951720-c7fe9c00-7adb-11ea-8358-961cd9db6ff5.png)

It is possible to check pixel difference with [ImageMagick](https://imagemagick.org/script/compare.php): `compare Cluster1.png Cluster2.png diff12.png`, it shows that there is no difference besides "Apply" button highlighting:

![image](https://user-images.githubusercontent.com/993454/78951797-08f6b080-7adc-11ea-8319-27a8e4a8b04f.png)

Then i change each point light size to 1 cm (one centimetre) as comment in source code suggests and i get this image without bright spots:

![image](https://user-images.githubusercontent.com/993454/78951904-6428a300-7adc-11ea-9d49-070452dd4b0f.png)

Difference (`compare Cluster1.png Cluster3.png diff13.png`):

![image](https://user-images.githubusercontent.com/993454/78951937-87535280-7adc-11ea-828a-69b21e66dca9.png)

There are still some spots, it's possibly not as smooth as zero-size lights, maybe better solution would be to enable point lights of zero radius, also change to attenuation function might be buggy or incorrect, but for now that's not the main point.

I think there might be a bug in attenuation and possibly in linked paper as well.

Is it something worth pursuing to a pull request or nah? It's not a big deal, it is possible to work this around by changing attenuation function as well, so it's whatever, i'm just asking.

**Comment by alekseyt** [comment]
Patch that was used to produce images above:

```diff
diff --git a/src/Renderer/Shaders/fs_clustered.sc b/src/Renderer/Shaders/fs_clustered.sc
index 45174ae..da5e64f 100644
--- a/src/Renderer/Shaders/fs_clustered.sc
+++ b/src/Renderer/Shaders/fs_clustered.sc
@@ -37,7 +37,7 @@ void main()
         uint lightIndex = getGridLightIndex(grid.offset, i);
         PointLight light = getPointLight(lightIndex);
         float dist = distance(light.position, fragPos);
-        float attenuation = smoothAttenuation(dist, light.radius);
+        float attenuation = smoothAttenuation(dist, light.size, light.radius);
         if(attenuation > 0.0)
         {
             vec3 L = normalize(light.position - fragPos);
diff --git a/src/Renderer/Shaders/fs_deferred_pointlight.sc b/src/Renderer/Shaders/fs_deferred_pointlight.sc
index d8c5cde..50dc69d 100644
--- a/src/Renderer/Shaders/fs_deferred_pointlight.sc
+++ b/src/Renderer/Shaders/fs_deferred_pointlight.sc
@@ -43,7 +43,7 @@ void main()
     light.position = mul(u_view, vec4(light.position, 1.0)).xyz;
     
     float dist = distance(light.position, fragPos);
-    float attenuation = smoothAttenuation(dist, light.radius);
+    float attenuation = smoothAttenuation(dist, light.size, light.radius);
     if(attenuation > 0.0)
     {
         vec3 V = normalize(-fragPos);
diff --git a/src/Renderer/Shaders/fs_forward.sc b/src/Renderer/Shaders/fs_forward.sc
index 8f02c92..ee7374e 100644
--- a/src/Renderer/Shaders/fs_forward.sc
+++ b/src/Renderer/Shaders/fs_forward.sc
@@ -34,7 +34,7 @@ void main()
     {
         PointLight light = getPointLight(i);
         float dist = distance(light.position, fragPos);
-        float attenuation = smoothAttenuation(dist, light.radius);
+        float attenuation = smoothAttenuation(dist, light.size, light.radius);
         if(attenuation > 0.0)
         {
             vec3 L = normalize(light.position - fragPos);
diff --git a/src/Renderer/Shaders/lights.sh b/src/Renderer/Shaders/lights.sh
index 18c3fe3..aa85ddc 100644
--- a/src/Renderer/Shaders/lights.sh
+++ b/src/Renderer/Shaders/lights.sh
@@ -10,19 +10,16 @@ uniform vec4 u_lightCountVec;
 uniform vec4 u_ambientLightIrradiance;
 
 // for each light:
-//   vec4 position (w is padding)
+//   vec4 position + size (xyz is position, w is size)
 //   vec4 power + radius (xyz is power, w is radius)
 BUFFER_RO(b_pointLights, vec4, SAMPLER_LIGHTS_POINTLIGHTS);
 
 struct PointLight
 {
     vec3 position;
-    // this padding is necessary for Vulkan when using the struct in a shared workgroup array
-    // otherwise memory reads/writes are corrupted
-    // I can't find where this is required per the spec so I'll assume this is a bug with Nvidia drivers/HW
-    float _padding;
+    float size; // size of light source (i.e. source's own radius)
     vec3 intensity;
-    float radius;
+    float radius; // effective light radius (i.e. distance from source covered by light)
 };
 
 struct AmbientLight
@@ -37,21 +34,22 @@ struct AmbientLight
 
 #define INV_4PI 0.07957747154
 
-float distanceAttenuation(float distance)
+float distanceAttenuation(float distance, float size)
 {
     // only for point lights
 
     // physics: inverse square falloff
-    // pretend point lights are tiny spheres of 1 cm radius
-    return 1.0 / max(distance * distance, 0.01 * 0.01);
+    // pretend point lights are tiny spheres of <size> radius
+    // with hard cutoff at 0.01 (1 cm)
+    return 1.0 / max((distance - size + 1) * (distance - size + 1), 0.01 * 0.01);
 }
 
-float smoothAttenuation(float distance, float radius)
+float smoothAttenuation(float distance, float size, float radius)
 {
     // window function with smooth transition to 0
     // radius is arbitrary
     float nom = saturate(1.0 - pow(distance / radius, 4.0));
-    return nom * nom * distanceAttenuation(distance);
+    return nom * nom * distanceAttenuation(distance, size);
 }
 
 uint pointLightCount()
@@ -62,7 +60,9 @@ uint pointLightCount()
 PointLight getPointLight(uint i)
 {
     PointLight light;
-    light.position = b_pointLights[2 * i + 0].xyz;
+    vec4 positionSizeVec = b_pointLights[2 * i + 0];
+    light.position = positionSizeVec.xyz;
+    light.size = positionSizeVec.w;
     vec4 powerRadiusVec = b_pointLights[2 * i + 1];
     light.intensity = powerRadiusVec.xyz * INV_4PI;
     light.radius = powerRadiusVec.w;
diff --git a/src/Scene/LightList.cpp b/src/Scene/LightList.cpp
index f87a213..b50981e 100644
--- a/src/Scene/LightList.cpp
+++ b/src/Scene/LightList.cpp
@@ -29,6 +29,7 @@ void PointLightList::update()
     {
         PointLightVertex* light = (PointLightVertex*)(mem->data + (i * stride));
         light->position = lights[i].position;
+        light->size = 1;
         light->power = lights[i].power;
         light->radius = lights[i].calculateRadius();
     }
diff --git a/src/Scene/LightList.h b/src/Scene/LightList.h
index c28eb87..fdd8f87 100644
--- a/src/Scene/LightList.h
+++ b/src/Scene/LightList.h
@@ -10,7 +10,7 @@ struct LightList
     struct PointLightVertex
     {
         glm::vec3 position;
-        float padding;
+        float size;
         glm::vec3 power;
         float radius;
```

**Comment by alekseyt** [comment]
And patch to disable rng on lights:

```diff
diff --git a/src/Cluster.cpp b/src/Cluster.cpp
index 957d701..8355759 100644
--- a/src/Cluster.cpp
+++ b/src/Cluster.cpp
@@ -396,7 +396,7 @@ void Cluster::generateLights(unsigned int count)
 
     std::random_device rd;
     std::seed_seq seed = { rd() };
-    std::mt19937 mt(seed);
+    std::mt19937 mt(0);
     std::uniform_real_distribution<float> dist(0.0f, 1.0f);
 
     for(size_t i = keep; i < count; i++)
```

**Comment by pezcode** [comment]
> i still believe that this is not the size of light source, but a cutoff where attenuation stops growing towards infinity.

That's exactly what it is. I'm not sure if I misunderstand you or vice versa, but maybe my drawing skills can help us understand each other :D

![Untitled](https://user-images.githubusercontent.com/907940/79011300-093a8e80-7b64-11ea-93d0-2cf660fb2188.png)

Point lights have no "size", they are infinitesimally small. Otherwise they'd only start emitting light after a certain distance away from their position. The light intensity is defined at 1m distance, because you have to define it *somewhere* and then attenuate it based on the distance from that reference.

> If this member is used for size, then this can be possibly resolved externally by setting up another light size which is considered most appropriate.

What do you mean by size then? Size should be governed by the radius property. It's calculated somewhat arbitrarily (see `PointLight::calculateRadius`), because real lights don't have a fixed radius. The windowing function makes sure it transitions to 0 softly, but that's obviously not physically correct. It's only needed for efficient culling.

I'm not sure if that addresses your questions, feel free to elaborate a bit more if not. I might not have entirely understand the underlying motivation behind the change you made.

**Comment by alekseyt** [comment]
Actually your picture shows exactly what i'm talking about. Sorry for not being able to communicate this clearly and thank you for your patience.

![image](https://user-images.githubusercontent.com/993454/79023669-8c221000-7b89-11ea-8fa3-c49b81a09d1b.png)

By size i mean radius of that "light bulb" outlined with blue color. This "bulb" is displayed on rendered images as bright spot of white light. I assume because falloff > 1 isn't falloff, inverse square law says that density of flux should decrease, not increase, so it's just a "light bulb" with flux higher than going out off "light bulb" surface.

So at distance 1m light always will be at max power (max flux), then falloff accordingly to inverse square law - as expected. What is not quite expected is that there always a 1m sphere of white light around each point light.

So i though this float that is currently used for padding could be used to adjust "light bulb" size, to make it smaller, like 1cm. This way light will start to falloff sooner, but it's possible to increase power to compensate for that.

Does that make sense?

**Comment by alekseyt** [comment]
Or maybe i'm wrong at "at distance 1m light always will be at max power (max flux)".

![image](https://user-images.githubusercontent.com/993454/79024684-5fbbc300-7b8c-11ea-888c-ae0ba950cae3.png)

In my understanding, defined power/flux/luminosity/whatever of light should be equal to power as observed from the light's surface. Maybe my understanding is incorrect, or maybe some part of power is lost inside of the "bulb", but then i don't understand where bright spots are coming from.

If it's a blue light, then i would assume that spot is going to be blue too, not white.

![image](https://user-images.githubusercontent.com/993454/79025092-81697a00-7b8d-11ea-978a-9dc7c3222b75.png)

**Comment by alekseyt** [comment]
~~Here i rendered lights in grayscale:~~

![image](https://user-images.githubusercontent.com/993454/79026190-ae6b5c00-7b90-11ea-9908-90ec9a23823f.png)

~~There are anomalies (in this case - dark spots) in the middle of every light.~~

My mistake, it was due to my other local changes.

**Comment by pezcode** [comment]
Physically speaking, it doesn't make sense to define intensity at any distance from the surface, since it's defined as the flux travelling in a cone that spans one steradian. Doesn't matter how far away you go from a point light, it's still the same amount of flux and the same angle, just the sphere surface spanned by the cone gets bigger. But we're not dealing with cones, we're dealing with pixels. So we define that at 1m from the light source 1 pixel = 1 steradian. As you get closer, the angle/surface spanned by the pixel increases proportionally to 1/r².

The 1cm cutoff for attenuation is really only there to keep it from exploding to infinity, and the (incorrect) comment isn't helping there 👀

This may be completely wrong, since I'm by no means an expert at this and still get confused by all the different quantities and units. But it's how I visualize it. Related note: the code uses radiometric quantities, which is wrong. I should change that to photometric quantities at some point.

The bright spots appear because colors aren't really R/G/B only so even small values in one channel end up 'saturating' the framebuffer with high enough values. Together with tonemapping this emulates what actually happens in real life, colors desaturating with brightness. If you try only generating R/G/B only lights (and possibly turn off color mapping) you shouldn't be seeing white spots unless lights overlap.

**Comment by alekseyt** [comment]
OK, after you repeated this 3 times i've got it. So 1cm cutoff doesn't play any role in lights except solving particular math problem, got it, one less misunderstanding.

I think another misunderstanding is that color of that spots matters, real problem is the existence of that spots, not their color. I have point lights less than 1m, if "bulb" is always one meter - it's going to illuminate more than needed because there is simply no falloff before 1m, before that falloff > 1, right?

Is there a way to properly represent point light that illuminates less than 1m? I guess i can decrease power and that way light will have less radius (range) and affect less clusters, OK, but falloff of that light is still going to be > 1 before distance reaches 1m and it will be brighter than needed. No?

**Comment by pezcode** [comment]
Changing flux/power is the *physically correct* way of influencing brightness (and indirectly, radius, but that's not a physical quantity of a light as photons will travel infinitely far). If the brightness at any point is *too bright* for you, then you picked a flux value that's too high.  Pick a lightbulb from any hardware store, plug in the lumens and it should come out "correct".

Had to read up a bit on this myself again and found this nice resource: https://www.compuphase.com/electronics/candela_lumen.htm Basically, 1 candela (flux per solid angle [steradian]) equals 1 lux (flux per area [m²]) at 1m radius. That correlation allows us to convert from intensity to illumination and actually calculate the light arriving at a pixel. My understanding is that this is why the 1m is implicit for calculating falloff. Falloff is not some magical property that makes all lights a minimum of 1m in radius.

But let me be honest: I've read the Frostbite and Unreal documents and it made intuitive sense, but I didn't derive any of this myself. I don't claim to truly understand every aspect of the formulas. If in doubt, crossreference with the Frostbite docs and the Filament source, since those people got paid to do the math 😄

**Comment by alekseyt** [comment]
I think there is still some misunderstanding. I don't see units as a problem here, but i'll go through this link regardless.

So i have a point light of some size and i want it to illuminate everything around it in range of about 0.5m. I can adjust power parameter and this indeed will influence range, directly or indirectly, in some way. Fragment shader (and shader library) doesn't work with power or flux anyway, it only works with radius (range), right? So power/flux/luminescence are not really important when rendering, only indirectly, just as you said, i heard you.

In current implementation, at some ranges lights are going to have spots that i don't want, if range is decreased, spots will go away, but light is not going to illuminate same range anymore. So it seems that i can only have either large lights with spots or smooth lights without spots, but very small smooth lights. Or larger lights with larger spots.

This is physically correct, isn't it? Just like you said in first comment. Perhaps we're doing circles in this discussion, this is not good. What really confuses me is this 1m magic number, attenuation function works differently before and after that distance for some reason. But whatever.

Essentially all i want is to tweak parameters and hack lights into looking the way i want them to look really. Maybe own attenuation function is the best way to go here. I'll go through all your suggestions and all the links. Thank you very much for looking into this.

**Comment by pezcode** [comment]
You **can** set the light power from the CPU. Excerpt from the random light generation code: https://github.com/pezcode/Cluster/blob/6e1ff057fb931344ab1bc52270dd1fd176ca6344/src/Cluster.cpp#L411
This isn't just a color, but the actual luminous power/flux, and in the fragment shader it's multiplied with the attenuation factor and the BRDF.

But yes, if you have a powerful light that illuminates far away, if you have a fragment close to it, it'll be very bright. What you might want to play around with is the code that calculates the windowing radius: https://github.com/pezcode/Cluster/blob/6e1ff057fb931344ab1bc52270dd1fd176ca6344/src/Scene/Light.cpp#L7 It's a total hack, and in any proper game engine this would be artist controlled anyway.

Re: 1m magic number. It's not behaving one way, then another. It's more like saying water at 5m depth has a pressure of X. Going up and down will change the pressure by a factor Y. Same math, just different direction.

**Comment by alekseyt** [comment]
orz
